version: "3.6"

services:
  vehicle_registration_api:
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    env_file: .env
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - .data/mongo:/data/db
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    # mongo logs clutter stdout in my opinion.
    # Comment out the logging section here to re-enable logs.
    logging:
      driver: none
